"""add tile name_en

Revision ID: e919a5135e91
Revises: 2f450dd29562
Create Date: 2026-06-23 20:41:01.838079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e919a5135e91'
down_revision = '2f450dd29562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiosk_tile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiosk_tile', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
